{% set name = "openxr-sdk" %}
{% set version = "1.1.45" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/OpenXR-SDK/archive/release-{{ version }}.tar.gz
  sha256: 1e8684c80476bf5faefb94990cc9b34797032fabaeb29e0aa0fc337d30c12af8

build:
  number: 0
  skip: true  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make                               # [not win]
    - cmake
    - pkg-config
  host:
    - jsoncpp
    - xorg-libxfixes  # [linux]
    - libgl-devel  # [linux]
    - xorg-xorgproto  # [linux]

test:
  commands:
    - test -f ${PREFIX}/include/openxr/openxr.h  # [not win]
    - test -f ${PREFIX}/lib/libopenxr_loader.so  # [linux]
    - test -f ${PREFIX}/lib/cmake/openxr/OpenXRConfig.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\openxr\\openxr.h (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\openxr_loader.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\openxr_loader.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\cmake\\OpenXRConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/KhronosGroup/OpenXR-SDK
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenXR headers and loader.

extra:
  recipe-maintainers:
    - traversaro
